import type { autosleep, bluetooth } from '../../../../wailsjs/go/models';
import type { LanguagePreference } from '../../i18n.svelte';

export interface PreferenceSettingsModel {
  autoSleep: autosleep.Settings | null;
  autoSleepError?: string | null;
  autoSleepBusy?: boolean;
  scanOnStartup: boolean | null;
  scanOnStartupError?: string | null;
  scanOnStartupBusy?: boolean;
  scanDurationSeconds: number | null;
  scanDurationError?: string | null;
  scanDurationBusy?: boolean;
  statusPollingEnabled: boolean | null;
  statusPollingEnabledError?: string | null;
  statusPollingEnabledBusy?: boolean;
  statusPollIntervalSeconds: number | null;
  statusPollIntervalError?: string | null;
  statusPollIntervalBusy?: boolean;
  languagePreference?: LanguagePreference;
  languageBusy?: boolean;
  onAutoSleepChange: (settings: autosleep.Settings) => void;
  onAutoSleepRetry?: () => void;
  onScanOnStartupChange: (enabled: boolean) => void;
  onScanOnStartupRetry?: () => void;
  onScanDurationChange: (durationSeconds: number) => void;
  onScanDurationRetry?: () => void;
  onStatusPollingEnabledChange: (enabled: boolean) => void;
  onStatusPollingEnabledRetry?: () => void;
  onStatusPollIntervalChange: (intervalSeconds: number) => void;
  onStatusPollIntervalRetry?: () => void;
  onLanguageChange?: (language: LanguagePreference) => void;
}

export interface OperationSettingsModel {
  bulkPowerTimeoutSeconds: number | null;
  bulkPowerTimeoutError?: string | null;
  bulkPowerTimeoutBusy?: boolean;
  stationOperationTimeoutSeconds: number | null;
  stationOperationTimeoutError?: string | null;
  stationOperationTimeoutBusy?: boolean;
  powerConfirmAttemptsOn: number | null;
  powerConfirmAttemptsOnError?: string | null;
  powerConfirmAttemptsOnBusy?: boolean;
  powerConfirmAttemptsOff: number | null;
  powerConfirmAttemptsOffError?: string | null;
  powerConfirmAttemptsOffBusy?: boolean;
  powerConfirmPollIntervalMs: number | null;
  powerConfirmPollIntervalError?: string | null;
  powerConfirmPollIntervalBusy?: boolean;
  bootFallbackSeconds: number | null;
  bootFallbackError?: string | null;
  bootFallbackBusy?: boolean;
  sleepFinalWriteTimeoutSeconds: number | null;
  sleepFinalWriteTimeoutError?: string | null;
  sleepFinalWriteTimeoutBusy?: boolean;
  sleepPrepareGapMs: number | null;
  sleepPrepareGapError?: string | null;
  sleepPrepareGapBusy?: boolean;
  discoveryAttempts: number | null;
  discoveryAttemptsError?: string | null;
  discoveryAttemptsBusy?: boolean;
  discoveryRetryDelayMs: number | null;
  discoveryRetryDelayError?: string | null;
  discoveryRetryDelayBusy?: boolean;
  powerWriteAttempts: number | null;
  powerWriteAttemptsError?: string | null;
  powerWriteAttemptsBusy?: boolean;
  operationRetryDelayMs: number | null;
  operationRetryDelayError?: string | null;
  operationRetryDelayBusy?: boolean;
  identifyAttempts: number | null;
  identifyAttemptsError?: string | null;
  identifyAttemptsBusy?: boolean;
  confirmReconnectThreshold: number | null;
  confirmReconnectThresholdError?: string | null;
  confirmReconnectThresholdBusy?: boolean;
  confirmReconnectDelayMs: number | null;
  confirmReconnectDelayError?: string | null;
  confirmReconnectDelayBusy?: boolean;
  onBulkPowerTimeoutChange: (timeoutSeconds: number) => void;
  onBulkPowerTimeoutRetry?: () => void;
  onStationOperationTimeoutChange: (timeoutSeconds: number) => void;
  onStationOperationTimeoutRetry?: () => void;
  onPowerConfirmAttemptsOnChange: (attempts: number) => void;
  onPowerConfirmAttemptsOnRetry?: () => void;
  onPowerConfirmAttemptsOffChange: (attempts: number) => void;
  onPowerConfirmAttemptsOffRetry?: () => void;
  onPowerConfirmPollIntervalChange: (intervalMs: number) => void;
  onPowerConfirmPollIntervalRetry?: () => void;
  onBootFallbackChange: (fallbackSeconds: number) => void;
  onBootFallbackRetry?: () => void;
  onSleepFinalWriteTimeoutChange: (timeoutSeconds: number) => void;
  onSleepFinalWriteTimeoutRetry?: () => void;
  onSleepPrepareGapChange: (gapMs: number) => void;
  onSleepPrepareGapRetry?: () => void;
  onDiscoveryAttemptsChange: (attempts: number) => void;
  onDiscoveryAttemptsRetry?: () => void;
  onDiscoveryRetryDelayChange: (delayMs: number) => void;
  onDiscoveryRetryDelayRetry?: () => void;
  onPowerWriteAttemptsChange: (attempts: number) => void;
  onPowerWriteAttemptsRetry?: () => void;
  onOperationRetryDelayChange: (delayMs: number) => void;
  onOperationRetryDelayRetry?: () => void;
  onIdentifyAttemptsChange: (attempts: number) => void;
  onIdentifyAttemptsRetry?: () => void;
  onConfirmReconnectThresholdChange: (threshold: number) => void;
  onConfirmReconnectThresholdRetry?: () => void;
  onConfirmReconnectDelayChange: (delayMs: number) => void;
  onConfirmReconnectDelayRetry?: () => void;
}

export interface AdvancedSettingsModel {
  apiListenAddress: string | null;
  apiListenAddressError?: string | null;
  apiListenAddressBusy?: boolean;
  channelConfirmAttempts: number | null;
  channelConfirmAttemptsError?: string | null;
  channelConfirmAttemptsBusy?: boolean;
  channelConfirmIntervalMs: number | null;
  channelConfirmIntervalError?: string | null;
  channelConfirmIntervalBusy?: boolean;
  presenceMissThreshold: number | null;
  presenceMissThresholdError?: string | null;
  presenceMissThresholdBusy?: boolean;
  initialReadTimeoutSeconds: number | null;
  initialReadTimeoutError?: string | null;
  initialReadTimeoutBusy?: boolean;
  scanReadPhaseTimeoutSeconds: number | null;
  scanReadPhaseTimeoutError?: string | null;
  scanReadPhaseTimeoutBusy?: boolean;
  statusReadTimeoutSeconds: number | null;
  statusReadTimeoutError?: string | null;
  statusReadTimeoutBusy?: boolean;
  statusRefreshTimeoutSeconds: number | null;
  statusRefreshTimeoutError?: string | null;
  statusRefreshTimeoutBusy?: boolean;
  channelScanFreshnessSeconds: number | null;
  channelScanFreshnessError?: string | null;
  channelScanFreshnessBusy?: boolean;
  recoveryRetryBaseSeconds: number | null;
  recoveryRetryBaseError?: string | null;
  recoveryRetryBaseBusy?: boolean;
  recoveryRetryMaxSeconds: number | null;
  recoveryRetryMaxError?: string | null;
  recoveryRetryMaxBusy?: boolean;
  absentStationRetryLimit: number | null;
  absentStationRetryLimitError?: string | null;
  absentStationRetryLimitBusy?: boolean;
  bluetoothInitRetrySeconds: number | null;
  bluetoothInitRetryError?: string | null;
  bluetoothInitRetryBusy?: boolean;
  onAPIListenAddressChange: (address: string) => void;
  onAPIListenAddressRetry?: () => void;
  onChannelConfirmAttemptsChange: (attempts: number) => void;
  onChannelConfirmAttemptsRetry?: () => void;
  onChannelConfirmIntervalChange: (intervalMs: number) => void;
  onChannelConfirmIntervalRetry?: () => void;
  onPresenceMissThresholdChange: (threshold: number) => void;
  onPresenceMissThresholdRetry?: () => void;
  onInitialReadTimeoutChange: (timeoutSeconds: number) => void;
  onInitialReadTimeoutRetry?: () => void;
  onScanReadPhaseTimeoutChange: (timeoutSeconds: number) => void;
  onScanReadPhaseTimeoutRetry?: () => void;
  onStatusReadTimeoutChange: (timeoutSeconds: number) => void;
  onStatusReadTimeoutRetry?: () => void;
  onStatusRefreshTimeoutChange: (timeoutSeconds: number) => void;
  onStatusRefreshTimeoutRetry?: () => void;
  onChannelScanFreshnessChange: (freshnessSeconds: number) => void;
  onChannelScanFreshnessRetry?: () => void;
  onRecoveryRetryBaseChange: (baseSeconds: number) => void;
  onRecoveryRetryBaseRetry?: () => void;
  onRecoveryRetryMaxChange: (maxSeconds: number) => void;
  onRecoveryRetryMaxRetry?: () => void;
  onAbsentStationRetryLimitChange: (limit: number) => void;
  onAbsentStationRetryLimitRetry?: () => void;
  onBluetoothInitRetryChange: (retrySeconds: number) => void;
  onBluetoothInitRetryRetry?: () => void;
}

export interface BluetoothDiagnosticsModel {
  adapters: bluetooth.AdapterInfo[];
  loading: boolean;
  loadError: string | null;
  onRefresh: () => void;
}

export interface SettingsDrawerModel {
  preferences: PreferenceSettingsModel;
  operations: OperationSettingsModel;
  advanced: AdvancedSettingsModel;
  diagnostics: BluetoothDiagnosticsModel;
}

export interface SettingsDrawerProps {
  model: SettingsDrawerModel;
  inactive?: boolean;
  onClose: () => void;
}
