// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBulkPower() {
  return window['go']['main']['App']['CancelBulkPower']();
}

export function CheckAllStationStatuses() {
  return window['go']['main']['App']['CheckAllStationStatuses']();
}

export function GetAPIStatus() {
  return window['go']['main']['App']['GetAPIStatus']();
}

export function GetAutoSleepSettings() {
  return window['go']['main']['App']['GetAutoSleepSettings']();
}

export function GetBulkPowerTimeoutSeconds() {
  return window['go']['main']['App']['GetBulkPowerTimeoutSeconds']();
}

export function GetCurrentStationInfo() {
  return window['go']['main']['App']['GetCurrentStationInfo']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetScanStatus() {
  return window['go']['main']['App']['GetScanStatus']();
}

export function GetStatusPollIntervalSeconds() {
  return window['go']['main']['App']['GetStatusPollIntervalSeconds']();
}

export function IdentifyStation(arg1) {
  return window['go']['main']['App']['IdentifyStation'](arg1);
}

export function IsScanning() {
  return window['go']['main']['App']['IsScanning']();
}

export function ListBluetoothAdapters() {
  return window['go']['main']['App']['ListBluetoothAdapters']();
}

export function PowerOffAllStations() {
  return window['go']['main']['App']['PowerOffAllStations']();
}

export function PowerOffStation(arg1) {
  return window['go']['main']['App']['PowerOffStation'](arg1);
}

export function PowerOnAllStations() {
  return window['go']['main']['App']['PowerOnAllStations']();
}

export function PowerOnStation(arg1) {
  return window['go']['main']['App']['PowerOnStation'](arg1);
}

export function RefreshStationCapabilities(arg1) {
  return window['go']['main']['App']['RefreshStationCapabilities'](arg1);
}

export function RenameStation(arg1, arg2) {
  return window['go']['main']['App']['RenameStation'](arg1, arg2);
}

export function RenameStationByAddress(arg1, arg2) {
  return window['go']['main']['App']['RenameStationByAddress'](arg1, arg2);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function ScanAndFetchStations() {
  return window['go']['main']['App']['ScanAndFetchStations']();
}

export function SetAllStationsPower(arg1) {
  return window['go']['main']['App']['SetAllStationsPower'](arg1);
}

export function SetAllStationsPowerDetailed(arg1) {
  return window['go']['main']['App']['SetAllStationsPowerDetailed'](arg1);
}

export function SetAutoSleepSettings(arg1) {
  return window['go']['main']['App']['SetAutoSleepSettings'](arg1);
}

export function SetBulkPowerTimeoutSeconds(arg1) {
  return window['go']['main']['App']['SetBulkPowerTimeoutSeconds'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetStationChannel(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetStationChannel'](arg1, arg2, arg3);
}

export function SetStationPower(arg1, arg2) {
  return window['go']['main']['App']['SetStationPower'](arg1, arg2);
}

export function SetStatusPollIntervalSeconds(arg1) {
  return window['go']['main']['App']['SetStatusPollIntervalSeconds'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
