// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {station} from '../models';
import {main} from '../models';
import {autosleep} from '../models';
import {bluetooth} from '../models';

export function CancelBulkPower():Promise<void>;

export function CheckAllStationStatuses():Promise<Array<station.StationInfo>>;

export function GetAPIStatus():Promise<main.APIStatus>;

export function GetAutoSleepSettings():Promise<autosleep.Settings>;

export function GetBulkPowerTimeoutSeconds():Promise<number>;

export function GetCurrentStationInfo():Promise<Array<station.StationInfo>>;

export function GetLanguage():Promise<string>;

export function GetScanDurationSeconds():Promise<number>;

export function GetScanOnStartup():Promise<boolean>;

export function GetScanStatus():Promise<station.ScanStatus>;

export function GetStatusPollIntervalSeconds():Promise<number>;

export function GetStatusPollingEnabled():Promise<boolean>;

export function IdentifyStation(arg1:string):Promise<void>;

export function IsScanning():Promise<boolean>;

export function ListBluetoothAdapters():Promise<Array<bluetooth.AdapterInfo>>;

export function PowerOffAllStations():Promise<void>;

export function PowerOffStation(arg1:string):Promise<void>;

export function PowerOnAllStations():Promise<void>;

export function PowerOnStation(arg1:string):Promise<void>;

export function RefreshStationCapabilities(arg1:string):Promise<station.StationInfo>;

export function RenameStation(arg1:string,arg2:string):Promise<void>;

export function RenameStationByAddress(arg1:string,arg2:string):Promise<void>;

export function SaveConfig():Promise<void>;

export function ScanAndFetchStations():Promise<Array<station.StationInfo>>;

export function SetAllStationsPower(arg1:string):Promise<void>;

export function SetAllStationsPowerDetailed(arg1:string):Promise<station.BulkPowerResult>;

export function SetAutoSleepSettings(arg1:autosleep.Settings):Promise<void>;

export function SetBulkPowerTimeoutSeconds(arg1:number):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetScanDurationSeconds(arg1:number):Promise<void>;

export function SetScanOnStartup(arg1:boolean):Promise<void>;

export function SetStationChannel(arg1:string,arg2:number,arg3:boolean):Promise<station.ChannelChangeResult>;

export function SetStationPower(arg1:string,arg2:string):Promise<station.PowerActionResult>;

export function SetStatusPollIntervalSeconds(arg1:number):Promise<void>;

export function SetStatusPollingEnabled(arg1:boolean):Promise<void>;

export function StopScan():Promise<void>;
