// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {station} from '../models';
import {main} from '../models';

export function CheckAllStationStatuses():Promise<Array<station.StationInfo>>;

export function GetAPIStatus():Promise<main.APIStatus>;

export function GetCurrentStationInfo():Promise<Array<station.StationInfo>>;

export function GetScanStatus():Promise<station.ScanStatus>;

export function Greet(arg1:string):Promise<string>;

export function IdentifyStation(arg1:string):Promise<void>;

export function IsScanning():Promise<boolean>;

export function PowerOffAllStations():Promise<void>;

export function PowerOffStation(arg1:string):Promise<void>;

export function PowerOnAllStations():Promise<void>;

export function PowerOnStation(arg1:string):Promise<void>;

export function RefreshStationCapabilities(arg1:string):Promise<station.StationInfo>;

export function RenameStation(arg1:string,arg2:string):Promise<void>;

export function RenameStationByAddress(arg1:string,arg2:string):Promise<void>;

export function SaveConfig():Promise<void>;

export function ScanAndFetchStations():Promise<Array<station.StationInfo>>;

export function SetAllStationsPower(arg1:string):Promise<void>;

export function SetAllStationsPowerDetailed(arg1:string):Promise<station.BulkPowerResult>;

export function SetStationChannel(arg1:string,arg2:number,arg3:boolean):Promise<station.ChannelChangeResult>;

export function SetStationPower(arg1:string,arg2:string):Promise<station.PowerActionResult>;
